application: bia660-final
version: 1
api_version: 1
runtime: python27
threadsafe: true
 
handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: new-main.app

libraries:
- name: jinja2
  version: latest